# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    xcode_select("/Applications/Xcode-15.2.0.app")
  end
  
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Run Unit Tests"
  lane :unit_tests do
     #run_tests(scheme: "ElevenTenTests")
     #prelaunch_simulator: true
     #reset_simulator: true
     #
     scan(
      scheme: "ElevenTenTests",
      xcodebuild_formatter: "xcpretty",
      code_coverage: true,
      output_directory: "output/test_output/unit_tests",
      clean: true,
      parallel_testing: false,
      concurrent_workers: 2
     )
  end

  desc "Run UI Tests"
  lane :ui_tests do
    scan(
      scheme: "ElevenTenUITests",
      xcodebuild_formatter: "xcpretty",
      output_directory: "output/test_output/ui_tests",
      clean: true,
      parallel_testing: false,
      concurrent_workers: 2
)
  end
end
