# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    xcode_select("/Applications/Xcode-16.1.0.app")
  end

  desc "Run Unit Tests"
  lane :unit_tests do

     scan(
      scheme: "ElevenTen",
      testplan: "ElevenTenTestPlan",
      clean: true,
      reset_simulator: true,
      code_coverage: true,
      output_directory: "fastlane/test_output",
      output_types: "junit,html",
      fail_build: true,
      xcpretty_args: "--utf"
    )
  end

  desc "Run UI Tests"
  lane :ui_tests do
    scan(
      scheme: "ElevenTenUITests",
      xcodebuild_formatter: "xcpretty",
      output_directory: "output/test_output/ui_tests",
      clean: true,
      parallel_testing: false,
      concurrent_workers: 2
)
  end
end
