name: CI/CD for ElevenTen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run unit tests
        run: bundle exec fastlane unit_tests

      - name: Run test
        run: |
           xcodebuild test -scheme 'ElevenTenTests' -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1'
